### PR TITLE
[BUGFIX] Allow at-rules to be parsed in strict mode

### LINKED ISSUE #352: @media block gives syntax error
```
@media (min-width: 1220px) {
  div { width:auto; }
}
```

gives an "Syntax error in CSS: Identifier expected. Got “}” [line no: 3]"

This looks like a regression in version 8.4.0 - I'm suspecting https://github.com/sabberworm/PHP-CSS-Parser/pull/162

### PR DESCRIPTION
**Pull request by JakeQZ**
The reverts the change to `CSSList` in
https://github.com/MyIntervals/PHP-CSS-Parser/commit/134f4e62fe8ab9f316425f3c0f480b3f4f52d804 and adds a comment that `null` is an expected return value when the end of the list (or block) is reached.

Fixes #352

### CODE REVIEW

**Comment by JakeQZ** [comment]
> The reverts the change to `CSSList`

Or at least it should.  I found it impossible to copy and paste the previous version of the code from the GitHub diff, so went hunting for a specific version that should have contained the code to restore.  Only it didn't.  So it was a bit painstaking to actually revert that change.  Any tips to speed up the process would be greatly appreciated.

**Comment by JakeQZ** [comment]
`Could not open input file: .\.phive\phpcs.phar`

Can't fix this without knowing what the problems are.  And, of course, the PHIVE set-up is a total PITA.

**Comment by JakeQZ** [comment]
> `Could not open input file: .\.phive\phpcs.phar`
> 
> Can't fix this without knowing what the problems are. And, of course, the PHIVE set-up is a total PITA.

OK, fixed, using info from logs.

File: tests/ParserTest.php [hunk 1]
```diff
@@ -74,7 +74,10 @@ public function files()
                     // or a future test of a as-of-now missing feature
                     continue;
                 }
-                $oParser = new Parser(file_get_contents($sDirectory . '/' . $sFileName));
+                $oParser = new Parser(
+                    \file_get_contents($sDirectory . '/' . $sFileName),
+                    Settings::create()->withLenientParsing($sFileName[0] !== '=')
```
Comment (oliverklee) [inline tests/ParserTest.php:79]: Instead of having separate sets of fixtures with "magic" prefixes, I'd prefer to communicate this more clearly to the reader, e.g., with a separate testcase that uses the CSS in the test code instead of reading from files. (After all, one of the purposes of tests is to communicate the intended behavior to the reader).

**Review by oliverklee — CHANGES_REQUESTED** [review]

File: tests/ParserTest.php (hunk 1 above)
Comment (JakeQZ) [reply tests/ParserTest.php]: I've moved the new tests to the specific test class responsible.  When working within an IDE, having the test content as separate files is no probem, and helps avoid test class files with literally millions of lines to scroll through, which, even if it doesn't cause the computer to break down, is a bit of a PITA.

**Comment by JakeQZ** [comment]
Can't figure out how to remove the files I added that are no longer wanted.

**Comment by JakeQZ** [comment]
> Can't figure out how to remove the files I added that are no longer wanted.

Non-alphanumeric characters in filenames cause problems in OSs developed in the 1970s, that are still prevelant now.  So must be avoided.

**Comment by JakeQZ** [comment]
I want to convert this from draft to live.  But can't find whatever I need to do to do so.  Nothing hapens when I click the 'Draft' button.

**Comment by JakeQZ** [comment]
> Change the status to “Ready for review” near the bottom of your pull request to remove the draft state

Nope.  Don't see it.

**Comment by JakeQZ** [comment]
> > Change the status to “Ready for review” near the bottom of your pull request to remove the draft state
> 
> Nope. Don't see it.

Finally found it.  What an awful UI.  Thank you Microsoft.

File: tests/CSSList/AtRuleBlockListTest.php [hunk 2]
```diff
@@ -7,12 +7,46 @@
...
 
 /**
  * @covers \Sabberworm\CSS\CSSList\AtRuleBlockList
  */
 final class AtRuleBlockListTest extends TestCase
 {
+    /**
+     * @return array<string, array<int, string>>
+     */
+    public static function provideMinWidthMediaRule()
```
Comment (oliverklee) [inline tests/CSSList/AtRuleBlockListTest.php:20]:
```suggestion
    public static function provideMinWidthMediaRule(): array
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -19,6 +19,8 @@ This project adheres to [Semantic Versioning](https://semver.org/).
 
 ### Fixed
 
+Fix (regression) failure to parse at-rules with strict parsing (#456)
```
Comment (oliverklee) [inline CHANGELOG.md:22]:
```suggestion
- Fix (regression) failure to parse at-rules with strict parsing (#456)
```

File: tests/CSSList/AtRuleBlockListTest.php [hunk 4]
```diff
@@ -83,4 +106,19 @@ public function parsesArgumentsOfMediaQueries($css)
...
+
+    /**
+     * @test
+     *
+     * @param string $css
+     *
+     * @dataProvider provideMinWidthMediaRule
+     * @dataProvider provideSyntacticlyCorrectAtRule
+     */
+    public function parsesSyntacticlyCorrectAtRuleInStrictMode($css)
```
Comment (oliverklee) [inline tests/CSSList/AtRuleBlockListTest.php:118]:
```suggestion
    public function parsesSyntacticlyCorrectAtRuleInStrictMode(string $css): void
```

File: tests/CSSList/AtRuleBlockListTest.php [hunk 5]
```diff
@@ -83,4 +106,19 @@ public function parsesArgumentsOfMediaQueries($css)
 
         self::assertSame('(min-width: 768px)', $atRuleBlockList->atRuleArgs());
     }
+
+    /**
+     * @test
+     *
+     * @param string $css
```
Comment (oliverklee) [inline tests/CSSList/AtRuleBlockListTest.php:113]: We can drop the PHPDoc type annotations for cases where we now can use native type declarations instead.

File: tests/CSSList/AtRuleBlockListTest.php [hunk 6]
```diff
@@ -7,12 +7,46 @@
...
+        return [
+            'without spaces around arguments' => ['@media(min-width: 768px){.class{color:red}}'],
+            'with spaces around arguments' => ['@media (min-width: 768px) {.class{color:red}}'],
+        ];
+    }
+
+    /**
+     * @return array<string, array<int, string>>
+     */
+    public static function provideSyntacticlyCorrectAtRule()
```
Comment (oliverklee) [inline tests/CSSList/AtRuleBlockListTest.php:31]:
```suggestion
    public static function provideSyntacticlyCorrectAtRule(): array
```

File: tests/CSSList/AtRuleBlockListTest.php [hunk 7]
```diff
@@ -7,12 +7,46 @@
...
+    public static function provideMinWidthMediaRule()
+    {
+        return [
+            'without spaces around arguments' => ['@media(min-width: 768px){.class{color:red}}'],
+            'with spaces around arguments' => ['@media (min-width: 768px) {.class{color:red}}'],
+        ];
+    }
+
+    /**
+     * @return array<string, array<int, string>>
```
Comment (oliverklee) [inline tests/CSSList/AtRuleBlockListTest.php:29]:
```suggestion
     * @return array<string, array{0: string}>
```

File: tests/CSSList/AtRuleBlockListTest.php [hunk 8]
```diff
@@ -7,12 +7,46 @@
...
 use Sabberworm\CSS\Renderable;
+use Sabberworm\CSS\Settings;
 
 /**
  * @covers \Sabberworm\CSS\CSSList\AtRuleBlockList
  */
 final class AtRuleBlockListTest extends TestCase
 {
+    /**
+     * @return array<string, array<int, string>>
```
Comment (oliverklee) [inline tests/CSSList/AtRuleBlockListTest.php:18]:
```suggestion
     * @return array<string, array{0: string}>
```

**Review by oliverklee — CHANGES_REQUESTED** [review]

**Review by sabberworm — APPROVED** [review]

**Review by oliverklee — APPROVED** [review]
LGTM. :pray:

**Comment by JakeQZ** [comment]
Wondering it we should release an 8.5.1 with this fix, since it was a regression in 8.4.

**Comment by oliverklee** [comment]
Yeah, I think backporting it to 8.5.x makes sense. We probably need to change the native type declarations to PHPDoc annotations.

Would you be willing to create the backport PR?

And should we release 8.5.1 directly after merging it, or should we first collect some more fixes?

**Comment by JakeQZ** [comment]
> Yeah, I think backporting it to 8.5.x makes sense. We probably need to change the native type declarations to PHPDoc annotations.

Ah, yes, the 8.x branch supports older PHP versions which don't support native type declerations.
 
> Would you be willing to create the backport PR?

I should hopefully be able to merge the commit to main to a PR branch off the 8.x.  Then revert the type hint changes.

> And should we release 8.5.1 directly after merging it, or should we first collect some more fixes?

The other outstanding PRs awaiting review mostly don't look straightforward, and may require post-review changes, so may take some time to complete.

I was keen to resolve this issue as a priority since it was a regression.  The others aren't, AFAIAA, so it would be on a case-by-case basis whether they can be easily backported once completed on `main`.  So I'd suggest an 8.5.1 with this fix, and some time later when the outstanding PRs have been resolved one way or another, (probably) an 8.5.2 with a rollup of fixes from those.
