### PR TITLE
[BUGFIX] Fix the return type of `Selector::isValid()`

### LINKED ISSUE #1043: Have `Selector::isValid()` actually return a `bool`
Currently, is returns `int<0, max>|false`.

We also need to add test coverage for this method and add a native return type declaration.

### PR DESCRIPTION
**Pull request by oliverklee**
Fixes #1043
Part of #811

### CODE REVIEW

**Comment by oliverklee** [comment]
Blocked by #1175.

**Review by JakeQZ — APPROVED** [review]

File: src/Property/Selector.php [hunk 1]
```diff
@@ -37,13 +37,13 @@ class Selector implements Renderable
...
     /**
-     * @return bool
-     *
      * @internal since V8.8.0
      */
-    public static function isValid(string $selector)
+    public static function isValid(string $selector): bool
     {
-        return \preg_match(static::SELECTOR_VALIDATION_RX, $selector);
+        $numberOfMatches = \preg_match(self::SELECTOR_VALIDATION_RX, $selector);
```
Comment (JakeQZ) [inline src/Property/Selector.php:44]: This needs to be `static` because `KeyframeSelector` overrides the `SELECTOR_VALIDATION_RX` constant to also allow keyframe animation percentage.

**Review by JakeQZ — CHANGES_REQUESTED** [review]
The failing test is because this breaks keyframes parsing, and is not related to the vendor prefix.  It just so happens that the keyframes test was written with a vendor prefix, and no equivalent test was written without a vendor prefix.

File: src/Property/Selector.php (hunk 1 above)
Comment (oliverklee) [reply src/Property/Selector.php:44]: Ah, that's why. Fix coming up …

**Review by JakeQZ — APPROVED** [review]
